### ISSUE TITLE
Menu button disappears on window resize

### ISSUE THREAD

**Issue by imbalino** [WaeCo/Coffee-light#24]
Both in chrome and firefox 
![d7b47819](https://user-images.githubusercontent.com/14980868/29360834-0a7a2308-8285-11e7-9b75-12b4ef0e4fa7.PNG)

**Comment by Peter42** [comment]
The problem occurs when the window is between 960 and 1280 pixel width.
Caused by the template I used. I was aware of it, but forgot to fix.
