### ISSUE TITLE
Display nope replies

### ISSUE THREAD

**Issue by Cheffu** [WaeCo/Coffee-light#27]
The initiator gets a popup with all the people that accepted his/her requests. However, the initiator doesn't get a message when someone clicks on "Nope". It would make sense to show this, because it would differentiate between people that did not react (or did not get get message) and people that don't want to come along. At the moment, the Nope answer doesn't make any sense as there is no difference between canceling the popup and clicking on Nope.

**Comment by Peter42** [comment]
fixed with https://github.com/WaeCo/Coffee-light/commit/6d975618113d25a6c4214154154886066482f84e
