### ISSUE TITLE
Websocket API for Notifications

### ISSUE THREAD

**Issue by Peter42** [WaeCo/Coffee-light#4]
- Refactor API to support multiple push services (WebPush, WebSocket, TBD), e.g. via callback function
- Implement a WebSocket push service.

**Comment by Niels-Be** [comment]
WebSocket Endpoint is `/websocket`

Message exchange is in JSON format. 

Towards Server:
```
{
  subscribe: { channelId, password },
  unsubscribe: { channelId }
}
```
Towards Client:
```
{
  error: { err },
  notification: { notification message },
  data: { name, channel, timestamp }
}
```

**Comment by Peter42** [comment]
Nice
