### ISSUE TITLE
401 on first request

### ISSUE THREAD

**Issue by Peter42** [WaeCo/Coffee-light#8]
The first pageload failes.
![image](https://user-images.githubusercontent.com/1571820/28233791-b3869422-68f9-11e7-887d-fb9e70e0d31c.png)
A refresh does the job.

**Comment by Niels-Be** [comment]
there is a race condition between `getSubscriptions` and `loginOnServer`.
`loginOnServer` is called in app.js:128 once firebase login competes.
`getSubscriptions` is called once scope is loaded.

We have to define some kind of delay or a callback to ensure `getSubscriptions` gets called after `loginOnServer` completed.

**Comment by Peter42** [comment]
@WaeCo exactly what I did, please review 10496fd
